### ISSUE TITLE
Feature request: Built-In SQL Storage Support

### ISSUE THREAD

**Issue by Rajaniraiyn** [awslabs/multi-agent-orchestrator#110]
### Use case

Enable support for SQL-based databases as built-in conversation storage to provide scalability, flexibility, and ease of integration with existing systems. This will cater to users managing large-scale conversations that require efficient querying, indexing, and handling of structured data.

### Solution/User Experience

Allow users to configure any SQL-based database (e.g., MySQL, PostgreSQL, SQLite) as the conversation storage backend.

### Alternative solutions

```markdown
Custom Storage can be implemented
```

**Comment by cornelcroi** [comment]
Done.
