### ISSUE TITLE
Feature request: Add support for Bedrock Flows

### ISSUE THREAD

**Issue by brnaba-aws** [awslabs/multi-agent-orchestrator#123]
### Use case

AWS Bedrock has a new feature: Bedrock Flows: https://aws.amazon.com/bedrock/flows/

### Solution/User Experience

There is no solution to orchestrate Bedrock Flows. MAO should support Bedrock Flows as one of their Agent to orchestrate them.

### Alternative solutions

```markdown
None
```

**Comment by cornelcroi** [comment]
Done https://github.com/awslabs/multi-agent-orchestrator/pull/125
