### ISSUE TITLE
Feature request: Add a Python Example Demonstrating Multi-Agent Orchestrator for NL2SQL

### ISSUE THREAD

**Issue by pierrehanne** [awslabs/multi-agent-orchestrator#132]
### Use case

Implement a Python-based example project showcasing how to leverage the capabilities of a multi-agent orchestrator for natural language to SQL (NL2SQL) tasks.

### Solution/User Experience

Enhance the cookbook with an additional use case to complement existing implementations.
- Load an open public dataset into a database (e.g., Amazon RDS PostgreSQL, Amazon Redshift, ...).
- Demonstrate the use of an agent equipped with tools to perform Text2SQL conversions, showcasing how user prompts can be transformed into actionable SQL queries.

This example will provide a practical illustration of the agent's capabilities in processing natural language inputs to interact with databases effectively.

**Comment by cornelcroi** [comment]
You can have a look at this [sample code](https://github.com/awslabs/multi-agent-orchestrator/tree/main/examples/text-2-structured-output

It does not do text to sql but text to structured output (json).
You can use the same approach to generate SQL.
