### ISSUE TITLE
Feature request: Add API call Actions/Action Group to retreivers

### ISSUE THREAD

**Issue by baldcodr** [awslabs/multi-agent-orchestrator#142]
### Use case

To build RAG applications, a user should also have the option to specify a set of actions an agent can perform to deliver desired results to end users as an alternative to a knowledge base.

### Solution/User Experience

These Actions/Action Groups can be a set of API call in a schema definition. With this, an agent can perform operations like to quickly retrieve available data via an API endpoint.

**Comment by brnaba-aws** [comment]
Hi @baldcodr,
Thanks for your interest in the multi-agent-orchestrator. 
You can implement your own [Retriever](https://awslabs.github.io/multi-agent-orchestrator/retrievers/overview/) if you like.
In the documentation we provided an example using Amazon Open Search. You can leverage this code and adapt it to your use case.
Let us know if you need more information.
Thanks,
Anthony

**Comment by brnaba-aws** [comment]
@baldcodr 
Does it answer your question? I'll close this issue if we don't hear anything back from you.
Thanks

**Comment by cornelcroi** [comment]
Closing the issue due to inactivity from the owner.
