### ISSUE TITLE
Feature request: Add support for Multi-Agent Collaboration with Amazon Bedrock Agents

### ISSUE THREAD

**Issue by maxritter** [awslabs/multi-agent-orchestrator#154]
### Use case

It would be great if the library supports creation of supervisor / collaborator agents as announced during Re:Invent 2024: https://docs.aws.amazon.com/bedrock/latest/userguide/agents-multi-agent-collaboration.html

### Solution/User Experience

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/bedrock-agent/client/create_agent.html has the "agentCollaboration" parameter and there are other methods like https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/bedrock-agent/client/associate_agent_collaborator.html to associate a collaborator to a supervisor

**Comment by brnaba-aws** [comment]
Hi @maxritter ,
Thanks for using the Multi agent orchestrator.
I just want to clarify that we are not linked to the Bedrock Agent Collaboration.
Our framework doesn't create any resources. You create resources and you can bring them into the orchestrator.
As per Multi agent collaboration, the agent is an Bedrock Agent and bedrock agent is already supported as part of the framework: https://awslabs.github.io/multi-agent-orchestrator/agents/built-in/amazon-bedrock-agent/

So if you have created a Bedrock Multi agent collaboration agent, and you want to orchestrate it along with other agents that you have, you can already do so in the orchestrator.

Let me know if this clarify.

Anthony

**Comment by maxritter** [comment]
Hey @brnaba-aws,
thanks a lot for the clarification, now I understand it!
Best,
Max

**Comment by Kundan547** [comment]
Hello everyone, I appreciate you setting up this forum for important conversations!

My name is Kundan Vyas, and I love technology and creativity. I think that by sharing my knowledge of full-stack programming, cloud optimisation (particularly on AWS), and AI-powered products, I can benefit this community.
Start fascinating conversations by posing challenging questions about topics such as effective CI/CD pipeline integration or methods for growing web apps.
Discuss my thoughts and experiences working on projects like creating a sign language translator with AI and automating processes to save cloud expenses.
Participate in the community to share your distinct viewpoints and work together on projects.
I'm eager to offer my experience and absorb knowledge from everyone.

**Comment by cornelcroi** [comment]
Hi,

We just released this new built in Agent: Supervisor Agent 
https://awslabs.github.io/multi-agent-orchestrator/agents/built-in/supervisor-agent/
