### ISSUE TITLE
Bug: BedrockInlineAgent and BedrockInlineAgentOptions not in index.d.ts

### ISSUE THREAD

**Issue by Flolight** [awslabs/multi-agent-orchestrator#158]
### Expected Behaviour

I should be able to import BedrockInlineAgent and BedrockInlineAgentOptions using the following:
```ts
import { BedrockInlineAgent, type BedrockInlineAgentOptions } from 'multi-agent-orchestrator';
```

### Current Behaviour

This is not working as both BedrockInlineAgent and BedrockInlineAgentOptions are not exxported inside the index.d.ts.

### Code snippet

```python
import { BedrockInlineAgent, type BedrockInlineAgentOptions } from 'multi-agent-orchestrator';
```

### Possible Solution

Adding the following to the index.d.ts is solving the issue:
```ts
export { BedrockInlineAgent, BedrockInlineAgentOptions } from './agents/bedrockInlineAgent';
```

### Steps to Reproduce

- Try to import in a ts file like this:
```ts
export { BedrockInlineAgent, BedrockInlineAgentOptions } from './agents/bedrockInlineAgent';
```

**Comment by brnaba-aws** [comment]
fixed in #159
