### ISSUE TITLE
Dead Link to API reference section

### ISSUE THREAD

**Issue by wwwmaster1** [awslabs/multi-agent-orchestrator#179]
https://github.com/awslabs/multi-agent-orchestrator/blame/b2037fad796579a5eaf3c5f131778866a8a2b50e/docs/src/content/docs/orchestrator/overview.mdx#L216

**Comment by cornelcroi** [comment]
I appreciate you bringing this to our attention, @wwwmaster1 . 
We've now fixed the page by removing the broken link and adding code snippets.
