### ISSUE TITLE
Feature request:  AWS Lambda-Compatible Python Version of Multi-Agent Orchestrator

### ISSUE THREAD

**Issue by valentin-dirken** [awslabs/multi-agent-orchestrator#27]
### Use case

I am working on integrating the Multi-Agent Orchestrator into a serverless architecture using AWS Lambda. My goal is to leverage AWS Lambda's scalability and cost-efficiency while utilizing the orchestrator's powerful multi-agent capabilities. However, deploying and managing the orchestrator within the AWS Lambda environment presents challenges, particularly with handling asynchronous operations and adapting to Lambda’s execution model.

### Solution/User Experience

I would like to request a version of the orchestrator which can be deployed as a Lambda function.

**Comment by valentin-dirken** [comment]
`import uuid
import json
import asyncio
from typing import Optional, List, Dict, Any
from multi_agent_orchestrator.orchestrator import MultiAgentOrchestrator, OrchestratorConfig
from multi_agent_orchestrator.agents import (BedrockLLMAgent,
                        BedrockLLMAgentOptions,
                        AgentResponse,
                        AgentCallbacks)
from multi_agent_orchestrator.types import ConversationMessage, ParticipantRole

class BedrockLLMAgentCallbacks(AgentCallbacks):
    def on_llm_new_token(self, token: str) -> None:
        # For Lambda, streaming output will not be directly printed; consider storing or handling differently.
        pass

async def handle_request(_orchestrator: MultiAgentOrchestrator, _user_input: str, _user_id: str, _session_id: str) -> Dict[str, Any]:
    response: AgentResponse = await _orchestrator.route_request(_user_input, _user_id, _session_id)
    
    result = {
        "agent_name": response.metadata.agent_name,
        "streaming": response.streaming,
        "response_text": response.output.content[0]['text']
    }
    
    return result

def lambda_handler(event: Dict[str, Any], context: Any) -> Dict[str, Any]:
    # Initialize the orchestrator with some options
    orchestrator = MultiAgentOrchestrator(options=OrchestratorConfig(
        LOG_AGENT_CHAT=True,
        LOG_CLASSIFIER_CHAT=True,
        LOG_CLASSIFIER_RAW_OUTPUT=True,
        LOG_CLASSIFIER_OUTPUT=True,
        LOG_EXECUTION_TIMES=True,
        MAX_RETRIES=3,
        USE_DEFAULT_AGENT_IF_NONE_IDENTIFIED=True,
        MAX_MESSAGE_PAIRS_PER_AGENT=10
    ))

    # Add some agents
    tech_agent = BedrockLLMAgent(BedrockLLMAgentOptions(
        name="Tech Agent",
        streaming=True,
        description="Specializes in technology areas including software development, hardware, AI, cybersecurity, blockchain, cloud computing, emerging tech innovations, and pricing/costs related to technology products and services.",
        model_id="anthropic.claude-3-sonnet-20240229-v1:0",
        callbacks=BedrockLLMAgentCallbacks()
    ))
    orchestrator.add_agent(tech_agent)

    user_input = event.get('user_input', '')
    user_id = event.get('user_id', 'user123')
    session_id = event.get('session_id', str(uuid.uuid4()))

    # Run the async function
    loop = asyncio.get_event_loop()
    response = loop.run_until_complete(handle_request(orchestrator, user_input, user_id, session_id))

    return {
        "statusCode": 200,
        "body": json.dumps(response)
    }
`

{
  "errorMessage": "Syntax error in module 'lambda_function': invalid syntax (base_events.py, line 296)",
  "errorType": "Runtime.UserCodeSyntaxError",
  "requestId": "",
  "stackTrace": [
    "  File \"/opt/python/asyncio/base_events.py\" Line 296\n            future = tasks.async(future, loop=self)\n"
  ]
}

**Comment by cornelcroi** [comment]
Hi,

You can use the framework anywhere, in a Lambda Function included.
There is a demo app included in the repository where the framework is used in a Lambda function.
Have a look at the code here `https://github.com/awslabs/multi-agent-orchestrator/blob/main/examples/chat-demo-app/lambda/multi-agent/index.ts`.

The framework does not need anything special to be done in order to work inside a lambda.
Can you tell me more about the `challenges, particularly with handling asynchronous operations and adapting to Lambda’s execution model.`.

What is the runtime of the Lambda you want to have?
If `typescript` the code should be helpful.
Or `python`?

**Comment by cornelcroi** [comment]
I just made some changes to the documentation and now there is a section on how to use it inside a Lambda Function in python
https://awslabs.github.io/multi-agent-orchestrator/deployment/aws-lambda-py/

Check it out and let me know if it helps.

**Comment by valentin-dirken** [comment]
Hi, 
Thank you ! I'm checking the code.

In the meantime : 

- I propose that you add this command for Windows
`Compress-Archive -Path .\* -DestinationPath ..\deployment-package.zip
`

- Regarding "Set the runtime to Python 3.8 or later.", it's **minimum 3.12**.
https://github.com/awslabs/multi-agent-orchestrator/blob/e25419487942f6c9e05b699b6fadd1d02a9b0109/python/setup.cfg#L21

**Comment by cornelcroi** [comment]
Thank you for letting me know. 
The documentation about using the framework inside a lambda function is mainly to show how the framework can be imported and used. Regarding the errors on the Lambda function itself you should check the official documentation.
I've updated the documentation to highlight this point.
