### ISSUE TITLE
Update error on documentation with toolSpec usage example

### ISSUE THREAD

**Issue by hghandri** [awslabs/multi-agent-orchestrator#34]
### Expected Behaviour

Update the documentation because I found a writing error.

### Current Behaviour

We've got an error :  

I found out an error on toolSpec, we must have a class dict type with "tools" key and after that an class list with each toolSpec

This cause a validation error from Bedrock API : 

Invalid type for parameter toolConfig, value: [{'toolSpec': {'name': 'xxxx', 'description': "xxxx", 'inputSchema': {'json': {'type': 'object', 'properties': {'field1': {'type': 'string', 'description': 'xxxx'}}, 'required': ['field1']}}}}], type: <class 'list'>, valid types: <class 'dict'>

### Code snippet

```python
nothing just see a change on documentation
```

### Steps to Reproduce

Configure Bedrock LLM Agent with tools with Python

**Comment by brnaba-aws** [comment]
After some investigation, we found out that there is an implementation mismatch between python and TS.
The documentation is fine, but we had to change the code to align with the TS version.

**Comment by brnaba-aws** [comment]
The commit [d6e369c](https://github.com/awslabs/multi-agent-orchestrator/commit/d6e369c6901f80ee4d84fda5e4f4182598989aa4) fixed the issue
