### ISSUE TITLE
Bug: Issue Template References Incorrect Project Name

### ISSUE THREAD

**Issue by drobbins-ancile** [awslabs/multi-agent-orchestrator#42]
### Expected Behaviour

The feature request issue template references the `multi-agent-orchestrator` project instead of the `CloudFront Hosting Toolkit`.

### Current Behaviour

The template references the `CloudFront Hosting Tookit`.

### Code snippet

```python
N/A
```

### Possible Solution

Update all occurrences of "CloudFront Hosting Toolkit" to "multi-agent-orchestrator" in the feature request issue template.

### Steps to Reproduce

Start the issue creation workflow and choose "feature request".

**Comment by cornelcroi** [comment]
Thank you.
PR Merged.
