### ISSUE TITLE
Bug: TITLE Lambda Implementation instructions

### ISSUE THREAD

**Issue by davep76** [awslabs/multi-agent-orchestrator#63]
### Expected Behaviour

Please provide detailed lambda implementation instructions. 

### Current Behaviour

current documentation is not enough

### Code snippet

```python
Please provide detailed lambda implementation instructions.
```

### Steps to Reproduce

Tricky to follow

**Comment by brnaba-aws** [comment]
The lambda documentation has been updated https://awslabs.github.io/multi-agent-orchestrator/deployment/aws-lambda-py/
