### ISSUE TITLE
Bug: Multiple instances of the orchestrator with default classifier

### ISSUE THREAD

**Issue by cornelcroi** [awslabs/multi-agent-orchestrator#68]
### Expected Behaviour

To have a new instance of the orchestrator when used with default value for classifier

### Current Behaviour

The orchestrator becomes static

### Code snippet

```python
orchestrator = MultiAgentOrchestrator(options=OrchestratorConfig(
        LOG_AGENT_CHAT=True,
        LOG_CLASSIFIER_CHAT=True,
        LOG_CLASSIFIER_RAW_OUTPUT=True,
        LOG_CLASSIFIER_OUTPUT=True,
        LOG_EXECUTION_TIMES=True,
        MAX_RETRIES=3,
        USE_DEFAULT_AGENT_IF_NONE_IDENTIFIED=True,

        MAX_MESSAGE_PAIRS_PER_AGENT=10       
    ))
```

### Possible Solution

Better handle the default values initialization in the `init` of the orchestrator

### Steps to Reproduce

Instantiate the orchestrator several times. Issue easy to test with FastAPI.

**Comment by brnaba-aws** [comment]
Fixed in python 0.0.18
