### ISSUE TITLE
Feature request: Option to manually route to specific agent from list of agents available in orchestrator

### ISSUE THREAD

**Issue by Arun4you** [awslabs/multi-agent-orchestrator#71]
### Use case

Having something like targetAgent will help routing to a specific agent. 

    const agentResponse = await this.multiAgentOrchestrator.routeRequest(
      JSON.stringify(query),
      this.userId || "system",
      this.sessionId || "system",
      { targetAgent: agentName }
    );

### Solution/User Experience

This will be handy when the routing is conditional and we know which agent to be routed to, instead of relying on orchestrator all the time. 

### Alternative solutions

```markdown
The lambda has to be invoked seperately.
```

**Comment by cornelcroi** [comment]
Hi,

I'd like to better understand, are you looking to:

1. Create a direct routing system that handles all requests without using an LLM?
2. Set up targeted routing where specific userIds and sessionIds get directed to particular Agents?

Thanks.

**Comment by cornelcroi** [comment]
Closing this PR due to inactivity. Feel free to reopen if needed. Thanks!
