### ISSUE TITLE
Feature request: Support for Bedrock Agent sessionAttributes and promptSessionAttributes 

### ISSUE THREAD

**Issue by yhou-uk** [awslabs/multi-agent-orchestrator#81]
### Use case

In the invoke_agent method, the sessionAttributes parameter allows us to pass contextual information such as user IDs, JWT etc.. This feature enables the subsequent transmission of these attributes to Lambda functions within the agent's action group. By using sessionAttributes in this manner, we can use the provided data as credentials to interact with customer business APIs. 

### Solution/User Experience

The user provides user ID and JWT data in AmazonBedrockAgentOptions. Subsequently, this data is passed to the Bedrock agent invocation and then to the action group Lambda functions.

**Comment by brnaba-aws** [comment]
@yhou-uk I guess we can close this?

**Comment by yhou-uk** [comment]
Happy to close this issue.  Thank you @brnaba-aws !
