### ISSUE TITLE
Feature request: OpenAI Classifier

### ISSUE THREAD

**Issue by Rajaniraiyn** [awslabs/multi-agent-orchestrator#85]
### Use case

Enable the use of an inbuilt OpenAI classifier without the need to create a custom one.

### Solution/User Experience

Having an inbuilt OpenAI classifier would eliminate the need to write a custom classifier. This feature would enable seamless integration of OpenAI’s capabilities as a built-in classifier within the system, rather than requiring users to develop custom implementations.

### Alternative solutions

```markdown
We can currently create custom classifiers using the OpenAI SDK, but having it pre-integrated would improve usability and reduce overhead.
```

**Comment by brnaba-aws** [comment]
@Rajaniraiyn Can you also implement the python version of the classifier?
